texts={
    'saturday' : 'شنبه',
    'sunday' : 'یکشنبه',
    'monday' : 'دوشنبه',
    'tuesday' : 'سه شنبه',
    'wednesday' : 'چهارشنبه',
    'thursday'  : 'پنجشنبه',
    'friday'  :  'جمعه',
    '📅 Select day:' : '📅 لطفا روز مورد نظر را انتخاب کنید:',
    'file_not_found': '❌ فایلی یافت شد.',
    'choose log in if you have account, and sign up for creating a new account ⚠️': '⚠️ اگر اکانت دارید "ورود" و اگر ندارید "ثبت نام" را بزنید',
    'sign up completed ✅': 'ثبت نام با موفقیت انجام شد ✅',
    'sign up': 'ثبت نام',
    'log in': 'ورود',
    'enter your name: ': 'اسم خود را وارد کنین',
    'enter your last name: ': 'فامیلی خود را وارد کنین',
    'enter your password: ': 'پسورد خود را وارد کنین',
    'enter your phone number: ': 'شماره تماس خود را وارد کنین',
    'please share your correct number': 'لطفا شماره تلفن خودتون رو وارد کنین',
    'you signed up before ❌': 'شما قبلا ثبت نام کرده اید ❌',
    'first name is not correct': 'اسم اشتباه است ❌',
    'last name is not correct': 'فامیلی اشتباه است ❌',
    'password is not correct': 'رمز عبور اشتباه است ❌',
    'phone number is not correct': 'شماره تلفن اشتباه است ❌',
    'please sign up first': 'لطفا ابتدا ثبت نام کنید ❌',
    'send_file_info': '📁 لطفا فایل را با اطلاعات زیر در کپشن ارسال کنید:\n\n📛 نام فایل: [نام فایل]\n🏫 کلاس: [کلاس]\n📅 تاریخ: [1404/06/01]\n🕐 زنگ: [1/2/3/4]\n\nمثال:\nنام فایل: جزوه ریاضی فصل 1\nکلاس: 101\nتاریخ: 1404/06/01\nزنگ: 1',
    'schedule': 'برنامه هفتگی',
    'which weekend':'🗓 کدام هفته را میخواهید؟',
    'enter your username: ': 'نام کاربری خود را وارد کنین: ',
    'please use keyboard buttons': 'لطفا از دکمه ها استفاده کنین',
    'logout': '🚪 خروج از حساب',
    'upload_file': '📤 آپلود فایل جدید',
    'no_account': '❌ شما حسابی ندارید! لطفا ابتدا ثبت نام کنید.',
    'username is not correct': 'نام کاربری درست نیست ❌',
    'upload_success': '✅ فایل شما با موفقیت آپلود شد!',
    'back_to_menu': '🔙 برگشت به منوی اصلی',
    'please choose one': 'لطفاً یکی از گزینه‌ها را انتخاب کنید:',
    'please_select_command': '❌ لطفا ابتدا دستور را انتخاب کنید',
    'please_send_caption': 'لطفا فایل را با کپشن ارسال کنید',
    'profile': 'پروفایل من',
    'upload_failed': '❌ آپلود فایل ناموفق بود. دوباره تلاش کنید.',
    'send_admin_info': '📝 لطفا اطلاعات ادمین جدید را به این شکل ارسال کنید:\n\nCID: 123456789\nname: احمد\nlastname: احمدی\nphone: 09123456789\nusername: admin2\npassword: 1234',
    'only_teachers': '⚠️ فقط معلمان می‌توانند از این دستور استفاده کنند.',
    'logout_success': '✅ با موفقیت از حساب خود خارج شدید.\nبرای استفاده مجدد وارد شوید.',
    "you don't have acount": "❌ شما حسابی ندارید! لطفا ابتدا ثبت نام کنید."
}

commands = {
    'start': 'شروع ربات',
    'support': 'ارتباط با پشتیبانی',
    'help': 'راهنمای ربات',
}